"""The PATH sandbox itself: absent has to mean absent (#385, #472).

`_path_sandbox` is a fixture, and a fixture that quietly stops working takes
every suite built on it with it — silently, and in the direction that reads as
success. #472 is exactly that: three suites asserted what a stanza does with
`qb-claim` / `qb-release` / `qb-admit` missing, built their PATH out of
`dirname(bash)` to get `git` and `jq`, and on a home-manager install that
directory IS the profile directory holding those three tools. The absent branch
was never taken. A fourth suite passed anyway and had never taken it either.

So the module's guarantee is asserted here, on this host, with the real tools
installed — the configuration under which the old idiom failed. Two of these
tests would have caught #472 the day it was written.

Run: pytest harness/tests
"""

from __future__ import annotations

import io
import json
import os
import shutil
import subprocess
import sys
import tokenize
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent))

import _path_sandbox  # noqa: E402

TESTS = Path(__file__).resolve().parent

#: The two triple-quote openers, spelled without writing either of them
#: inside this file's own source.
TQ1, TQ2 = chr(34) * 3, chr(39) * 3

#: The suites whose subject is a tool being missing. They are named rather than
#: discovered because the property is about intent — a suite that asserts on an
#: absent tool owes its PATH to this module — and a discovered list would go
#: quiet the moment somebody spelled the absence differently.
ABSENCE_SUITES = (
    "test_create_worktree_claim.py",
    "test_create_worktree_bound.py",
    "test_prune_worktrees_claims.py",
    "test_remove_worktree_claim.py",
    # #528's three. Each asserted what happens with a `qb-*` missing while the
    # inherited PATH supplied it: `qb-catchup` ran once per run under a test
    # named "no qb-catchup on PATH", the `lonely-bin/` copy meant to defeat the
    # `${0%/*}` fallback was undone by the PATH beside it, and a deleted stub
    # `qb-claim` was replaced by the installed one.
    "test_qb_hook_end.py",
    "test_worktree_holder.py",
    "test_qb_start.py",
)

#: The wider set: every suite that hands a real harness script a whole
#: ENVIRONMENT. A superset of the above, because "the tool is absent" is only one
#: of the two ways a test can end up running production code — the other is
#: running a tool on purpose with the developer's credential still in reach, and
#: `test_remove_worktree_branch_guard.py` did exactly that for three authenticated
#: calls to the live board per run (#528). Absence is a PATH property; a
#: credential is a HOME one; both are built in `_path_sandbox`.
ISOLATED_SUITES = ABSENCE_SUITES + (
    "test_remove_worktree_branch_guard.py",
    "test_qbdata.py",
)

#: The bash member of the same class. It cannot import the module, so what is
#: pinned is that its two runners still hand the scripts an environment.
SHELL_SUITE = "create_worktree_nginx.test.sh"

#: The config file this box actually has, if it has one. Named here so the tests
#: below can assert a sandbox environment does not resolve to it — the property
#: is "not the developer's", and on a machine with no config at all there is
#: nothing to be wrong about, which is why the assertions that use this skip.
REAL_CONFIG = Path(
    os.environ.get("QUARTERBACK_CONFIG")
    or os.path.join(os.environ.get("XDG_CONFIG_HOME")
                    or os.path.expanduser("~/.config"), "quarterback", "config"))

#: A stand-in for it, in the shape the real one has on this fleet: comments, a
#: `_CMD` rather than a literal token, a value quoting `$HOME`, and a human URL.
#: Copied off the installed file rather than imagined — a fixture that invents the
#: shape of the thing it stands for is how #531 shipped twelve tests that could
#: not fail.
DECOY_CONFIG = """\
# Generated by home/scripts.nix — do not edit; edit the fleet and rebuild.
# Host: decoybox
QUARTERBACK_BASE_URL=http://decoy.invalid
QUARTERBACK_TOKEN_CMD="printf decoy-token"
QUARTERBACK_REPO="$HOME/source/quarterback"
QUARTERBACK_HUMAN_URL=http://decoy-human.invalid
"""


def code_of(src: str) -> str:
    """`src` with its comments and docstrings blanked out, and nothing else.

    The coupling guard below is about what a suite DOES, and these files now
    explain at length what they no longer do — a ban that fired on its own
    explanation would be a guard nobody could document around.

    Comments and TRIPLE-quoted strings only. Blanking every string literal would
    be the tidier rule and it is wrong: `os.environ["PATH"]` is one of the banned
    idioms and it has a string inside it, so a guard that ate string literals
    would stop seeing the very thing it is looking for. Blanked in place rather
    than deleted, so everything else stays exactly where it was.
    """
    triples = (TQ1, TQ2)
    lines = src.splitlines(keepends=True)
    for tok in tokenize.generate_tokens(io.StringIO(src).readline):
        prose = tok.type == tokenize.COMMENT or (
            tok.type == tokenize.STRING
            and tok.string.lstrip("rbuRBUf").startswith(triples))
        if not prose:
            continue
        (first, col), (last, end) = tok.start, tok.end
        for row in range(first, last + 1):
            line = lines[row - 1]
            a = col if row == first else 0
            b = end if row == last else len(line.rstrip("\r\n"))
            lines[row - 1] = line[:a] + " " * (b - a) + line[b:]
    return "".join(lines).replace("'", '"')


# ----------------------------------------------------------- the guarantee

def test_no_harness_tool_resolves_on_a_sandbox_path(tmp_path):
    """The property the three failing suites believed they had.

    Asserted against every command `harness/bin` ships, not the three that
    happened to break: #385's point is that the class grows — each new `qb-*`
    with a "what if this is missing" test becomes an instance the day it reaches
    a profile directory.
    """
    bindir = tmp_path / "bin"
    bindir.mkdir()
    path = _path_sandbox.sandbox_path(tmp_path, bindir, tools=("git", "jq", "tr"))
    found = {t: shutil.which(t, path=path) for t in _path_sandbox.harness_tools()}
    assert not {k: v for k, v in found.items() if v is not None}


def test_the_tools_asked_for_are_there_and_nothing_else_is(tmp_path):
    """A sandbox that resolved nothing would pass the test above and fail every
    stanza that shells out — which is how this suite's own sibling first ran,
    green about a sweep that had swept nothing."""
    bindir = tmp_path / "bin"
    bindir.mkdir()
    path = _path_sandbox.sandbox_path(tmp_path, bindir, tools=("git", "tr"))
    assert shutil.which("git", path=path)
    assert shutil.which("tr", path=path)
    assert shutil.which("jq", path=path) is None, "a tool nobody asked for"
    assert shutil.which("bash", path=path) is None


def test_python3_is_the_interpreter_running_this_suite(tmp_path):
    """The rollback in `create-worktree` releases THROUGH qbdata's own client, so
    two tests there need a real interpreter — and `python3` is not necessarily on
    PATH at all, either inside a nix build sandbox or under the very run a
    developer uses to check this class of bug (`PATH` with the profile stripped).
    """
    box = _path_sandbox.toolbox(tmp_path, ("python3",))
    assert (box / "python3").resolve() == Path(sys.executable).resolve()


def test_a_directory_this_test_did_not_fill_is_refused(tmp_path):
    """#472's actual line, rejected. `dirname(bash)` reads as "somewhere the
    basics live" and is in fact "wherever this host installed bash", which on the
    fleet is the directory the harness installs into."""
    bindir = tmp_path / "bin"
    bindir.mkdir()
    with pytest.raises(AssertionError, match="is not under"):
        _path_sandbox.sandbox_path(
            tmp_path, bindir, os.path.dirname(shutil.which("bash")))


def test_a_stub_the_test_wrote_is_not_a_leak(tmp_path):
    """The other half: a suite stubbing `qb-release` in its own bin directory is
    doing the intended thing, and a guard that could not tell that apart from a
    profile directory would be unusable."""
    bindir = tmp_path / "bin"
    bindir.mkdir()
    (bindir / "qb-release").write_text("#!/bin/sh\nexit 0\n")
    (bindir / "qb-release").chmod(0o755)
    path = _path_sandbox.sandbox_path(tmp_path, bindir)
    assert shutil.which("qb-release", path=path) == str(bindir / "qb-release")


def test_a_tool_this_host_has_not_got_is_an_error_not_a_silent_gap(tmp_path):
    """A missing symlink would read to the stanza as "the tool is broken", and the
    test would report that as the behaviour under test."""
    with pytest.raises(_path_sandbox.ToolMissing):
        _path_sandbox.toolbox(tmp_path, ("no-such-binary-anywhere",))


def test_the_scripts_own_directory_holds_no_harness_tool(tmp_path):
    """PATH is only half of the leak: each stanza falls back to `${0%/*}/qb-<tool>`
    when `command -v` finds nothing, so the directory the script file sits in is a
    second PATH of one entry."""
    d = _path_sandbox.sibling_dir(tmp_path)
    assert d.is_dir()
    (d / "qb-release").write_text("")
    with pytest.raises(AssertionError):
        _path_sandbox.sibling_dir(tmp_path)


def test_the_tool_list_is_read_from_harness_bin(tmp_path):
    """An empty list would make every assertion above pass while guarding
    nothing — #163's mechanism, and the reason it is asserted rather than
    assumed."""
    tools = _path_sandbox.harness_tools()
    assert {"qb-claim", "qb-release", "qb-admit"} <= set(tools)
    assert "qbdata.py" not in tools, "a module, not a command on PATH"


# ------------------------------------------------------------- the coupling

@pytest.mark.parametrize("name", ISOLATED_SUITES)
def test_the_isolated_suites_build_their_environment_here(name):
    """The guard that keeps this fix from being undone one file at a time.

    Each of these hands a real harness script an environment: a PATH on which a
    tool is deliberately missing, a HOME with deliberately no credential in it,
    or both. Hand-building either is the defect coming back, and it comes back
    green.
    """
    src = code_of((TESTS / name).read_text())
    assert "_path_sandbox" in src, f"{name} builds its own environment again"
    # Every spelling of "and then whatever the host has", not just the one #472
    # was written in. A sweep of this tree found the same defect wearing each of
    # them — the PATH, and with it the HOME, arrives by inheritance rather than
    # by name, which reads as harmless at the call site and is the identical
    # leak. `os.environ.items()` and `**os.environ` are #528's additions: two
    # more ways to spell the copy, and the two the suites this pass fixed used.
    for banned in ("os.path.dirname(BASH)", "os.path.dirname(JQ)",
                   "os.path.dirname(TR)", 'os.environ["PATH"]',
                   "dict(os.environ)", "os.environ.copy()",
                   "os.environ.items()", "**os.environ"):
        assert banned not in src, (
            f"{name} carries {banned} into a script it starts — on a host where "
            "the harness is installed that supplies the tool the test says is "
            "absent (#472) and the credential it says is not there (#528)")


def test_the_guard_reads_the_code_and_not_the_prose_around_it():
    """`code_of` is the guard's eyesight, and a guard that has quietly gone blind
    reports the thing it watches for as absent — which reads as success.

    Both directions, because the two plausible bugs fail in opposite ways: a
    blanker that starts at column 0 takes the code in front of a trailing comment
    with it, and one that eats every string takes `os.environ["PATH"]` apart.
    """
    src = ("x = dict(os.environ)  # the idiom, in code, with prose after it\n"
           "def f():\n"
           "    " + TQ1 + "dict(os.environ) named in a docstring is not a use."
           + TQ1 + "\n"
           "    return os.environ[\"PATH\"]\n")
    code = code_of(src)
    assert code.count("dict(os.environ)") == 1, "the docstring was counted as code"
    assert 'os.environ["PATH"]' in code, "a string inside an expression was eaten"
    assert "named in a docstring" not in code
    assert "the idiom, in code" not in code


def test_the_shell_suite_hands_its_scripts_an_environment_too():
    """`create_worktree_nginx.test.sh` cannot import any of this, so its half of
    the property is pinned by reading it: both runners must set a HOME and a
    config path of their own before starting the real script. Before #528 they
    set neither, and each run of that file made an authenticated `GET /active`
    against the production board."""
    src = (TESTS / SHELL_SUITE).read_text()
    assert "sandbox_env(){" in src, f"{SHELL_SUITE} lost its environment helper"
    helper = src.split("sandbox_env(){", 1)[1].split("\n}", 1)[0]
    assert "unset QUARTERBACK_BASE_URL QUARTERBACK_TOKEN" in helper, (
        f"{SHELL_SUITE} stopped unsetting the shell's own board credentials")
    assert "export HOME=" in helper and "export QUARTERBACK_CONFIG=" in helper, (
        f"{SHELL_SUITE} stopped redirecting the config the scripts would read")
    for runner in ("run_create(){", "run_remove(){"):
        body = src.split(runner, 1)[1].split("\n}", 1)[0]
        assert "sandbox_env " in body, f"{SHELL_SUITE}'s {runner} starts a script bare"


# ------------------------------------------------- the environment guarantee

def board_url_seen(env: dict, reader: str) -> str | None:
    """What `reader` resolves as its board URL under `env`, or None for "none".

    Two readers, because there are two implementations of one rule and a helper
    that agreed with only the one it was written against would be worth nothing:
    `qbdata.resolve_config()` is what every python tool uses and `qb-env` is what
    every bash one does. Both are asked here rather than either being described.
    """
    if reader == "python":
        got = subprocess.run(
            [sys.executable, "-c",
             "import sys, json; sys.path.insert(0, sys.argv[1]);"
             "import qbdata;"
             # `base_url`, which is what BoardConfig actually calls it — read off
             # the class rather than guessed. The first draft of this said `url`
             # and the AttributeError is the only reason it is right now.
             "\ntry:\n c = qbdata.resolve_config()\n"
             " print(json.dumps({'url': c.base_url, 'token': c.token}))\n"
             "except RuntimeError:\n print(json.dumps(None))",
             str(_path_sandbox.BIN)],
            capture_output=True, text=True, env=env, timeout=60)
    else:
        # By absolute path: `subprocess` resolves the program against the PATH in
        # `env`, and half the environments handed to this helper deliberately
        # have a PATH with almost nothing on it.
        got = subprocess.run(
            [shutil.which("bash") or "/bin/bash", "-c",
             f'. {_path_sandbox.BIN}/qb-env; qb_load_config;'
             ' qb_resolve_token >/dev/null 2>&1;'
             ' printf "%s" "${QUARTERBACK_BASE_URL:-}"'],
            capture_output=True, text=True, env=env, timeout=60)
        return got.stdout.strip() or None
    assert got.returncode == 0, got.stderr
    answer = json.loads(got.stdout)
    return answer["url"] if answer else None


@pytest.mark.parametrize("reader", ["python", "bash"])
def test_a_sandbox_env_cannot_read_a_config_an_inherited_one_can(tmp_path, reader):
    """The property #528 is about, with its own live control.

    The control is the shape those five suites had: `os.environ` with `$HOME`
    moved. It finds the decoy — so this test can fail — and that is precisely
    what the real ones did with `$HOME` left alone, except that the file they
    found was the machine's own and the board it named was production.
    """
    decoy_home = tmp_path / "decoy-home"
    (decoy_home / ".config" / "quarterback").mkdir(parents=True)
    (decoy_home / ".config" / "quarterback" / "config").write_text(DECOY_CONFIG)

    inherited = {k: v for k, v in os.environ.items()
                 if not k.startswith("QUARTERBACK_")}
    inherited["HOME"] = str(decoy_home)
    inherited.pop("XDG_CONFIG_HOME", None)
    assert board_url_seen(inherited, reader) == "http://decoy.invalid", (
        "the control found no config, so this test could not have failed")

    isolated = _path_sandbox.sandbox_env(tmp_path, inherit_path=True)
    assert board_url_seen(isolated, reader) is None


def test_the_config_a_sandbox_env_resolves_is_not_the_developers(tmp_path):
    """Said as a path rather than as an outcome, so it holds on a machine with no
    board configured at all — where every "did it reach the board" assertion is
    vacuously true and would stay green through any regression."""
    env = _path_sandbox.sandbox_env(tmp_path)
    resolved = Path(_path_sandbox.config_path(env))
    assert tmp_path.resolve() in resolved.resolve().parents
    assert resolved != REAL_CONFIG
    assert not resolved.exists()


def test_a_credential_in_the_shell_is_not_carried_through(tmp_path, monkeypatch):
    """`QUARTERBACK_TOKEN` in the environment beats the config file, so a shell
    that exports one — which every agent session on this fleet does — hands it to
    anything a test starts, config isolation or no config isolation."""
    monkeypatch.setenv("QUARTERBACK_BASE_URL", "https://qb.example")
    monkeypatch.setenv("QUARTERBACK_TOKEN", "sekret")
    monkeypatch.setenv("QUARTERBACK_TOKEN_CMD", "printf sekret")
    monkeypatch.setenv("QUARTERBACK_HUMAN_KEY", "cookie")
    monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-nope")
    env = _path_sandbox.sandbox_env(tmp_path)
    assert "sekret" not in "\n".join(env.values())
    for gone in ("QUARTERBACK_BASE_URL", "QUARTERBACK_TOKEN",
                 "QUARTERBACK_TOKEN_CMD", "QUARTERBACK_HUMAN_KEY",
                 "ANTHROPIC_API_KEY"):
        assert gone not in env


def test_a_caller_can_still_name_the_board_it_means(tmp_path):
    """Half these suites run against a stub board on localhost. Isolation that
    made that impossible would be isolation nobody could use."""
    env = _path_sandbox.sandbox_env(tmp_path, QUARTERBACK_BASE_URL="http://127.0.0.1:9",
                                    QUARTERBACK_TOKEN="tok")
    assert env["QUARTERBACK_TOKEN"] == "tok"


def test_a_home_pointed_back_at_the_developer_is_refused(tmp_path):
    """The one mistake that undoes all of it, and the reason the check is in the
    function rather than in a test of the function."""
    with pytest.raises(AssertionError, match="points outside"):
        _path_sandbox.sandbox_env(tmp_path, HOME=os.path.expanduser("~"))


def test_the_pace_gate_is_off_unless_a_test_asks_for_it(tmp_path):
    """`qb-pace` reads the developer's own subscription and calls the usage
    endpoint, and `qb-seats` starts it by default. PATH cannot reach it — the
    fallback is `${0%/*}/qb-pace` inside `harness/bin` — so the knob is the seam.
    """
    assert _path_sandbox.sandbox_env(tmp_path)["QB_SEATS_PACE"] == "off"
    assert _path_sandbox.sandbox_env(tmp_path, QB_SEATS_PACE="obey")["QB_SEATS_PACE"] == "obey"


def test_the_path_guarantee_survives_the_environment_wrapper(tmp_path):
    """`sandbox_env` is the only thing most call sites now use, so the absence
    property has to hold through it as well as through `sandbox_path`."""
    bindir = tmp_path / "bin"
    bindir.mkdir()
    env = _path_sandbox.sandbox_env(tmp_path, bindir, tools=("git",))
    found = {t: shutil.which(t, path=env["PATH"]) for t in _path_sandbox.harness_tools()}
    assert not {k: v for k, v in found.items() if v is not None}
    assert shutil.which("git", path=env["PATH"])


def test_inherit_path_keeps_the_hosts_tools_and_none_of_its_credentials(tmp_path):
    """The escape hatch, and the half of the property it must NOT relax."""
    env = _path_sandbox.sandbox_env(tmp_path, inherit_path=True)
    assert shutil.which("bash", path=env["PATH"])
    assert Path(env["HOME"]).resolve().is_relative_to(tmp_path.resolve())
    assert not Path(_path_sandbox.config_path(env)).exists()


def test_an_empty_path_does_not_become_the_current_directory(tmp_path, monkeypatch):
    """An empty PATH entry means `.`, so joining a directory onto an absent PATH
    would put whatever the child's cwd happens to be on its own PATH."""
    monkeypatch.delenv("PATH", raising=False)
    env = _path_sandbox.sandbox_env(tmp_path, tmp_path / "bin", inherit_path=True)
    assert "" not in env["PATH"].split(os.pathsep)
