{ config, lib, pkgs, ... }:

let
  cfg = config.programs.quarterback-harness;
  share = "${cfg.package}/share/quarterback-harness";

  board = cfg.board;
  consumer = cfg.consumer;
  wantConfig = board.url != null;

  # The site config file, sourced (never executed) by qb-env — see harness/bin/qb-env for
  # the contract and for why there is no default board URL. Rendered here rather than left
  # to the consumer because "which board, which token" is the one thing that must be said
  # per host, and #230's whole complaint is that a consumer who says nothing gets nothing.
  #
  # QUARTERBACK_TOKEN_CMD is emitted inside SINGLE quotes so it stays literal until
  # qb_resolve_token evals it — which is what lets it reference $QUARTERBACK_AGENT, a
  # variable qb_load_config sets only AFTER sourcing this file. That is also why a single
  # quote inside the value is an assertion below and not a comment: it would terminate the
  # quoting and turn the rest of the command into config-file syntax.
  #
  # EVERY value is quoted, and the URL is the one that matters. This file is `source`d, so
  # a bare `QUARTERBACK_BASE_URL=https://a/b?x=1&y=2` ends the assignment at the `&` and
  # runs the remainder as a background command — on every board call, in every hook, on
  # every tool call, and the symptom is a host that silently never appears. `&`, `;`, `#`
  # and whitespace are all legal in a URL and none of them survives being unquoted.
  # Single quotes for the URL and the agent because neither has any business expanding
  # anything; double quotes for the repo because `$HOME` in it is the documented point.
  configText = ''
    # Generated by programs.quarterback-harness (quarterback's hm-module.nix).
    # Do not edit — change the nix and rebuild.
    QUARTERBACK_BASE_URL='${toString board.url}'
  '' + lib.optionalString (board.tokenCommand != null) ''
    QUARTERBACK_TOKEN_CMD='${board.tokenCommand}'
  '' + lib.optionalString (board.tokenRefreshCommand != null) ''
    QUARTERBACK_TOKEN_REFRESH_CMD='${board.tokenRefreshCommand}'
  '' + lib.optionalString (board.agent != null) ''
    QUARTERBACK_AGENT='${board.agent}'
  '' + lib.optionalString (board.repo != null) ''
    QUARTERBACK_REPO="${board.repo}"
  '' + lib.optionalString (consumer.flake != null) ''
    QUARTERBACK_CONSUMER_FLAKE="${consumer.flake}"
  '' + lib.optionalString (consumer.attr != null) ''
    QUARTERBACK_CONSUMER_ATTR='${consumer.attr}'
  '' + lib.optionalString (consumer.rebuild != null) ''
    QUARTERBACK_REBUILD_CMD='${consumer.rebuild}'
  '';

  # What `qb-start` compiles in (its SPAWNABLE table). Restated here so a bad
  # `spawn.commands` is an eval error naming the option rather than a refusal on a
  # box nobody is watching; `harness/tests/test_qb_start.py` fails if the two lists
  # ever disagree, which is the same guard `test_in_flight_drift.py` puts between
  # `qb-admit` and `harness_rules.DEFAULTS`.
  spawnableCommands = [
    "/investigate"
    "/fix-issue" "/fix-and-review" "/fix-and-land" "/review-pr" "/panel-review-pr"
    # Takes no number: it reads the plan and self-selects (#541). Allowing it
    # implies allowing everything it dispatches into — `qb-start` REFUSES a policy
    # that names this without `/fix-issue`, `/fix-and-land`, `/review-pr` and
    # `/panel-review-pr`, rather than granting them silently one hop along.
    "/get-involved"
  ];

  # The machine's spawn policy, read by `qb-start` and by nothing else. Written ONLY
  # when spawn.enable is true: the absence of this file is what "off" means, so a
  # host that has not opted in has nothing on disk for a bug to misread.
  spawnPolicy = builtins.toJSON {
    enabled = true;
    commands = cfg.spawn.commands;
    max_sessions = cfg.spawn.maxSessions;
    skip_permissions = cfg.spawn.skipPermissions;
  };

  # One message for every value that is emitted single-quoted, so a new one cannot be
  # added with the assertion forgotten.
  noSingleQuote = name: value: {
    assertion = value == null || !(lib.hasInfix "'" value);
    message = ''
      programs.quarterback-harness.${name} must not contain a single quote — it is
      emitted single-quoted into ~/.config/quarterback/config, which is sourced by every
      board client, and a quote inside it terminates the quoting and turns the rest of
      the line into shell. Use double quotes inside it, or wrap it in a script.
    '';
  };
in
{
  options.programs.quarterback-harness = {
    enable = lib.mkEnableOption "the quarterback agent harness (loops, worktree tooling, slash commands, board client)";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.callPackage ./package.nix { };
      defaultText = lib.literalExpression "pkgs.callPackage ./package.nix { }";
      description = "The harness package to install.";
    };

    commands = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "panel" "panel-review-pr" "review-pr"
        "epic" "lander" "loops" "fix-and-land" "fix-and-review"
        "fix-issue" "fix-issue-here" "get-involved"
        "wt" "drop-worktree" "tree-shake"
      ];
      description = ''
        Which slash commands to link into ~/.claude/commands. Defaults to all of
        them. Narrow it if the host already provides a command of the same name —
        home-manager will collide rather than silently pick a winner, which is
        the behaviour you want.
      '';
    };

    seats.enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Install the multiplexer `qb-seats` needs. The scripts themselves are in
        the package already — this only adds tmux, which is the one runtime
        dependency the harness cannot assume is present.

        Off by default, and that is deliberate rather than timid. A consumer
        typically enables this whole module once, for every host they own; a
        seat screen is something they want on ONE of them. Defaulting to on would
        push a package onto machines that will never run a seat — including work
        machines somebody else owns the disk of — as a side effect of enabling
        the loops and the worktree tooling, which is not a trade a default gets
        to make on their behalf.
      '';
    };

    # ---- may this machine start a session on its own? (#277) -----------------
    #
    # OFF, AND IT HAS TO BE A MACHINE THAT SAYS OTHERWISE. `qb-start` is a
    # remote-execution primitive on a box holding ~/.claude, ~/.config/gh and the
    # board token, so the switch lives here — in the module a person edits and
    # rebuilds — and nowhere a repository, an issue body or an agent can reach.
    # With `enable = false` the file below is not written at all, and `qb-start`
    # refuses before it has looked for a board, a token, a network or tmux.
    #
    # `commands` IS A SECOND LOCK and it is empty on purpose, the way
    # `issue_pickup.only_labels` is: turning spawning on is one decision, and
    # saying what may come through it is another. It can only ever NARROW
    # qb-start's compiled-in table (harness/bin/qb-start, SPAWNABLE) — a name
    # this module has never heard of is refused there, and the assertion below
    # refuses it here, at eval time, where the message can name the option.
    spawn = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Let `qb-start` begin an agent session on this machine. Off by default,
          and the default costs nothing: with this false, nothing is written to
          ~/.config/quarterback and `qb-start` exits 3 without consulting
          anything at all.

          What it permits is narrow by construction. The brief is a named slash
          command with a number — never free text — the session takes a board
          claim before the process exists, it runs in a real tmux window a human
          can attach to and interrupt, and it can be stopped with
          `qb-end <session>` from the moment it is created.
        '';
      };

      commands = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        example = [ "/fix-issue" "/panel-review-pr" ];
        description = ''
          Which commands this machine will start. Empty — the default — means
          none, so `spawn.enable` alone still spawns nothing.

          Must be a subset of what `qb-start` compiles in: /fix-issue,
          /fix-and-review, /fix-and-land, /review-pr, /panel-review-pr. A name
          outside that set is an eval error rather than a silent no-op.
        '';
      };

      maxSessions = lib.mkOption {
        type = lib.types.ints.unsigned;
        default = 1;
        description = ''
          How many spawned sessions may run on this machine at once. 0 is a
          freeze — legal, and it means admit nothing without taking the
          allowlist apart.

          The count is spawned tmux panes whose agent has not exited, so a
          window left open to read is not one of them.

          THE FALLBACK, not the only source (#563). The board's
          `spawn.max_sessions` dial answers first and this applies when no dial
          is set, when the board cannot be reached, or when what it holds is not
          a number — so a host with no dial behaves exactly as it did before.
          The other two keys here are permissions and deliberately have no such
          layer: whether this machine may spawn AT ALL, and what may come
          through the gate, must not depend on a board being reachable or on
          anything an agent can reach. A ceiling only counts a resource, dial
          writes are human-only, and needing a nix build, a PR and a rebuild to
          change a number is what this option is being relieved of.

          `qb-start --policy` reports the effective ceiling and names the layer
          that gave it.
        '';
      };

      skipPermissions = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Pass --dangerously-skip-permissions to a spawned agent. On by default,
          for a seat screen's reason: a spawned window is a pane nobody is watching,
          so the first tool call wanting a permission it does not hold stops it
          in the one way this cannot recover from — the pane looks busy, the
          board shows a live agent holding a claim, and nothing is moving.

          Turn it off and a spawn gets prompts back, which on an unattended pane
          means it stops at the first one.
        '';
      };
    };

    installScripts = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Put create-worktree / remove-worktree / prune-worktrees / worktree-holder
        on PATH by adding the package to home.packages. Turn this off to take the
        loops and commands without the worktree tooling — the two halves are
        independent.

        The board wiring below does NOT depend on this: it invokes qb-claude-setup
        by store path and wires qb-hook by store path, so a host can have a working
        board client without the harness on PATH at all. What it loses is the part a
        human types — `qb sessions`, `qb-board`, `create-worktree`.
      '';
    };

    # ---- which board, and how this host proves who it is ---------------------
    board = {
      url = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "https://qb.example.org";
        description = ''
          The board this host talks to. Setting it makes this module render
          `~/.config/quarterback/config`, which is what qb-hook, qb, qb-mcp and the
          status line all read.

          Null means "I manage that file myself" — the module renders nothing and
          collides with nothing. It does NOT mean a default board: there is
          deliberately no fallback URL anywhere in the harness. A self-hosted board
          has no sensible default, and guessing one points an agent at somebody
          else's board — which is not hypothetical, since a personal board resolves
          on public DNS from an employer's machine.
        '';
      };

      tokenCommand = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "cat /run/secrets/quarterback-token";
        description = ''
          A command printing this machine's bearer token on stdout. A command rather
          than a path because the token source is the other thing that varies per
          site — a file rendered by a secrets agent, a read from a password manager,
          an ssh fetch into RAM on a host that keeps no durable credential.

          Kept cheap: it runs on every board call. It is evaluated by the shell after
          the config file is sourced, so it may reference $QUARTERBACK_AGENT.
        '';
      };

      tokenRefreshCommand = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = ''
          Used INSTEAD of `tokenCommand` after a confirmed 401. It exists because the
          two are not always the same command: where `tokenCommand` reads a cache,
          re-running it after a rotation returns the same stale bearer, so the refresh
          has to go past the cache to the source of truth. Defaults to `tokenCommand`,
          which is right wherever that already reads the authoritative copy.
        '';
      };

      agent = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = ''
          This machine's name on the board — the machine half of a `machine/name`
          identity, and the name the token is issued against. Defaults to the short
          hostname, resolved at runtime rather than baked in.
        '';
      };

      repo = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "$HOME/source/quarterback";
        description = ''
          A checkout of this repository, which `qb-mcp` needs for the MCP server's venv
          (`mcp/.venv`). Emitted double-quoted, so `$HOME` in the value is expanded when
          the config is sourced. Null leaves qb-mcp's own default ($HOME/source/quarterback).

          That the MCP shim needs a checkout at all is a packaging gap, not a design:
          the server has real dependencies and lives beside the HTTP client it shares,
          so the flake does not build it yet.
        '';
      };
    };

    # ---- the wiring that makes a board client out of an installed package ----
    claude = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Wire the board into Claude Code's loose user configs at activation:
          the lifecycle hooks in `~/.claude/settings.json`, the stdio MCP server in
          `~/.claude.json`, and the workflow doc's @import in `~/.claude/CLAUDE.md`.
          This is what turns an installed harness into a working board client —
          without it a host gets the slash commands and the loops and no board:
          no lease, no presence, no ask courier, no overlap detection, no sync advice.

          Turn it off to take the fragment and merge it yourself. `qb-claude-setup
          --print-fragment` prints exactly what this would have merged, with paths
          resolved, so the manual route cannot drift from the wired one.
        '';
      };

      activationAfter = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        example = [ "claudeBaseSettings" ];
        description = ''
          Extra home-manager activation entries this module's wiring must run AFTER.

          Name your own here if you also write `~/.claude/settings.json`. The merge
          this module performs is additive by identity — it replaces quarterback's own
          hook entries and keeps everybody else's — but a merge that replaces whole
          arrays (`jq -s '.[0] * .[1]'`, the usual spelling) will drop ours if it runs
          last, because `hooks.PostToolUse` is an array. That is order-dependence, and
          order-dependence between two repos' activation scripts is a live bug class
          here rather than a hypothetical.

          Being explicit is the fix. Relying on the DAG's tie-breaking between two
          entries that merely both come after `writeBoundary` is not a fix; it is the
          same bug with a coincidence holding it up. `qb-claude-setup --check` reports
          the state either way, and reports it per event, so a wiring that lost one
          array is nameable rather than mysterious.
        '';
      };

      workflowDoc = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Install `~/.claude/quarterback-workflow.md` — how to use the board, for the
          model rather than for the machine — and @import it from `~/.claude/CLAUDE.md`.

          The import is conditional on the file being installed, so turning this off
          leaves no dangling @import behind. The file is a store symlink and therefore
          read-only, which is correct for a doc nothing local should be editing.

          `~/.claude/CLAUDE.md` is CREATED if you do not have one. Nothing else on a fresh
          host writes that file, so waiting for it would mean the doc shipped and no
          session ever read it — silently, and for the life of the machine.
        '';
      };

      registerMcp = lib.mkOption {
        type = lib.types.enum [ "auto" "always" "never" ];
        default = "auto";
        description = ''
          Register `qb-mcp` as a global stdio MCP server in `~/.claude.json`.

          `auto` registers it only when the shim could actually start — that is, when
          the interpreter it execs (`<board.repo>/mcp/.venv/bin/python`) exists. A
          registered server that cannot start means every session opens on a failed MCP
          connection, and `auto` self-heals on the next switch once the venv is built.
          `always` registers regardless, for a host that builds the venv after
          activation and would rather not switch twice.
        '';
      };
    };

    # ---- which flake CONSUMES this harness, so a bump can be prepared --------
    #
    # quarterback ships the harness; something else pins it. That something else is
    # a third thing — not this repo and not the store path — and `qb-doctor` records
    # that it cannot find it, which is why its staleness check compares CONTENT
    # rather than the pin. These two options are the door a consumer declares itself
    # through: set them and `qb-bump` knows, on this host, exactly which flake to
    # prepare a bump in and which system output to build. Leave them and it scans
    # (`~/source`, `~`) for a lock that pins this repo, which is what runs on a fleet
    # that has declared nothing — and refuses rather than guessing if it finds two.
    consumer = {
      flake = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "$HOME/source/nix-fleet";
        description = ''
          The flake that pins this harness — the checkout `nixos-rebuild --flake` is
          pointed at on this machine. Emitted as `QUARTERBACK_CONSUMER_FLAKE`.

          Point it at the CHECKOUT, not at a worktree of it: a machine is rebuilt from
          the former, and a bump prepared into the latter lands in somebody's in-flight
          branch. `$HOME` expands (the value is emitted double-quoted), which is what
          lets one fleet-wide line serve every host.
        '';
      };

      attr = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "desktop";
        description = ''
          The `nixosConfigurations` attribute that IS this machine, when it is not
          simply the hostname. Emitted as `QUARTERBACK_CONSUMER_ATTR`.

          Worth setting wherever the two differ, and only there. `qb-bump` uses an
          attribute NAMED AFTER this host without evaluating anything, so a fleet whose
          outputs are its hostnames needs nothing here. The fallback it falls back TO —
          evaluating each configuration in turn asking what hostname it declares — runs
          only when no attribute carries this host's name, and it is correct, slow, and
          defeatable by a host that does not evaluate here at all.
        '';
      };

      rebuild = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "rebuild switch";
        description = ''
          The command `qb-bump --apply` switches this machine with, when it is not
          `sudo nixos-rebuild switch --flake <consumer>#<attr>`. Emitted as
          `QUARTERBACK_REBUILD_CMD`.

          Leave it and `qb-bump` looks for a `rebuild` wrapper on PATH, READS it (never
          runs it), and uses it only when it names exactly one flake directory and that
          is the one just built — and only when the attribute was matched against this
          machine's hostname rather than named with `--host`, since a wrapper picks its
          own attribute from the hostname and nothing in its text can be checked against
          a named one. That covers this fleet, whose `rebuild` exists because
          `nixos-rebuild switch` prints "Done" over a failed `home-manager-<user>.service`,
          which is precisely how the harness scripts `qb-bump` delivers fail to arrive
          while the switch reports success.

          Set it on a host whose wrapper is named something else, or is assembled out of
          shell variables no read can resolve. Doing so is CONSENT: a declared command is
          used without the target check, because somebody has said what it builds.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    {
      # Every value that reaches ~/.config/quarterback/config is checked here, because the
      # failure a bad one causes is invisible: the file is sourced, so it fails as a *token
      # lookup* or as an unset URL at runtime, on every board call, with nothing pointing
      # back at the option that caused it. An eval-time refusal names the option instead.
      assertions = [
        (noSingleQuote "board.tokenCommand" board.tokenCommand)
        (noSingleQuote "board.tokenRefreshCommand" board.tokenRefreshCommand)
        (noSingleQuote "board.url" board.url)
        (noSingleQuote "board.agent" board.agent)
        (noSingleQuote "consumer.attr" consumer.attr)
        (noSingleQuote "consumer.rebuild" consumer.rebuild)
        {
          # The consumer keys ride in the file `board.url` decides to render, so
          # declaring one without the other is a value that silently reaches nothing —
          # and the symptom is `qb-bump` scanning, finding two candidates and refusing,
          # on a host that thought it had said which. Named at eval time instead.
          assertion = (consumer.flake == null && consumer.attr == null
            && consumer.rebuild == null) || wantConfig;
          message = ''
            programs.quarterback-harness.consumer is set but board.url is null, so this
            module renders no ~/.config/quarterback/config and the value would reach
            nothing. Set board.url, or write QUARTERBACK_CONSUMER_FLAKE into the config
            file you manage yourself.
          '';
        }
        {
          # Emitted double-quoted so that $HOME in it expands — the same trade board.repo
          # makes, and the same two characters it therefore cannot carry.
          assertion = consumer.flake == null
            || !(lib.hasInfix "\"" consumer.flake || lib.hasInfix "`" consumer.flake);
          message = ''
            programs.quarterback-harness.consumer.flake must not contain a double quote or
            a backtick — it is emitted double-quoted (so that $HOME in it expands) into
            ~/.config/quarterback/config, which every board client sources.
          '';
        }
        {
          # Refused at EVAL time, where the message can name the option, rather than
          # at spawn time on a box nobody is watching. `qb-start` refuses an unknown
          # command too — this is the same refusal moved to the moment a person can
          # read it, which is the whole argument for an allowlist over a filter.
          assertion = cfg.spawn.commands == []
            || (lib.subtractLists spawnableCommands cfg.spawn.commands) == [ ];
          message = ''
            programs.quarterback-harness.spawn.commands names ${
              lib.concatStringsSep ", " (lib.subtractLists spawnableCommands cfg.spawn.commands)
            }, which qb-start cannot start. It knows only: ${
              lib.concatStringsSep ", " spawnableCommands
            }.

            The set is compiled into harness/bin/qb-start (SPAWNABLE) because each
            entry carries the resource its session claims, and a command whose unit
            of work nobody has worked out is one that cannot be counted. This option
            narrows that set; it cannot widen it.
          '';
        }
        {
          # The one value emitted double-quoted, because `$HOME` in it is meant to expand.
          # That makes `"` and a backtick the characters it cannot carry.
          assertion = board.repo == null
            || !(lib.hasInfix "\"" board.repo || lib.hasInfix "`" board.repo);
          message = ''
            programs.quarterback-harness.board.repo must not contain a double quote or a
            backtick — it is emitted double-quoted (so that $HOME in it expands) into
            ~/.config/quarterback/config, which every board client sources.
          '';
        }
      ];

      # A board URL with no way to get a token is not an error — QUARTERBACK_TOKEN may
      # come from the environment on a host that keeps no credential of its own — but it
      # is almost always an oversight, and the failure is silent by design: qb-hook
      # no-ops when it cannot resolve a token, so the symptom is a host that simply
      # never appears on the board.
      warnings = lib.optional (wantConfig && board.tokenCommand == null) ''
        programs.quarterback-harness.board.url is set but board.tokenCommand is not.
        qb-hook resolves no token and will no-op silently, so this host will not appear
        on the board at all. Set board.tokenCommand, or export QUARTERBACK_TOKEN.
      '';

      home.packages =
        lib.optionals cfg.installScripts [ cfg.package ]
        # NOT wrapped into the package's PATH, unlike a build dependency would be.
        # The user attaches to tmux by hand, reattaches over ssh, and has their own
        # config for it — so it has to be the tmux they can see and configure, not
        # one hidden inside a wrapper where `tmux attach` from their own shell
        # would find a different binary.
        # A spawn IS a tmux window — there are no hidden sessions, so a host that
        # may start one needs the multiplexer whether or not it runs a seat screen.
        ++ lib.optionals (cfg.seats.enable || cfg.spawn.enable) [ pkgs.tmux ];

      home.file = lib.mkMerge (
        # ~/.claude/loops is a store symlink, i.e. READ-ONLY. epic.py already
        # accounts for this by writing its run state to ~/.local/state/loops rather
        # than beside itself; anything added here must do the same.
        [{ ".claude/loops".source = "${share}/loops"; }]
        ++ map
          (name: { ".claude/commands/${name}.md".source = "${share}/commands/${name}.md"; })
          cfg.commands
        ++ lib.optional (cfg.claude.enable && cfg.claude.workflowDoc) {
          ".claude/quarterback-workflow.md".source = "${share}/claude/quarterback-workflow.md";
        }
      );
    }

    # The site config: only when this module has been told which board. See board.url.
    (lib.mkIf wantConfig {
      xdg.configFile."quarterback/config".text = configText;
    })

    # The spawn policy: only when this machine has said it may start sessions. See
    # spawn.enable — the ABSENCE of this file is the default, and it is what makes
    # the default free rather than merely safe.
    (lib.mkIf cfg.spawn.enable {
      xdg.configFile."quarterback/spawn.json".text = spawnPolicy;
    })

    # ---- the activation ------------------------------------------------------
    # An activation script and not `home.file`, because ~/.claude/settings.json has
    # several writers — the user edits it, Claude Code writes to it, and nix wants to
    # declare parts of it. A store symlink would make it read-only and break the app.
    # qb-claude-setup carries the merge (and the reasoning); this only decides when it
    # runs and what is on its PATH.
    #
    # Named quarterbackClaudeWiring rather than the obvious quarterbackClaude: an
    # activation attribute is a shared namespace, a consumer migrating off a hand-rolled
    # copy of this wiring very likely has one of those, and two definitions of one
    # attribute is not a merge — it is a build that fails for everyone who pins this.
    (lib.mkIf cfg.claude.enable {
      home.activation.quarterbackClaudeWiring =
        lib.hm.dag.entryAfter ([ "writeBoundary" ] ++ cfg.claude.activationAfter) ''
          export PATH="${lib.makeBinPath [ pkgs.jq pkgs.gnugrep pkgs.coreutils pkgs.diffutils ]}:$PATH"
          # `|| true`: a coordination board must never be the reason a switch fails. The
          # script is fail-soft internally too — this is the second belt, for the case
          # where it cannot even start.
          $DRY_RUN_CMD ${pkgs.bash}/bin/bash ${cfg.package}/bin/qb-claude-setup \
            --mcp ${cfg.claude.registerMcp} || true
        '';
    })
  ]);
}
