{ config, lib, pkgs, ... }:

let
  cfg = config.programs.quarterback-harness;
  share = "${cfg.package}/share/quarterback-harness";

  board = cfg.board;
  wantConfig = board.url != null;

  # The site config file, sourced (never executed) by qb-env — see harness/bin/qb-env for
  # the contract and for why there is no default board URL. Rendered here rather than left
  # to the consumer because "which board, which token" is the one thing that must be said
  # per host, and #230's whole complaint is that a consumer who says nothing gets nothing.
  #
  # QUARTERBACK_TOKEN_CMD is emitted inside SINGLE quotes so it stays literal until
  # qb_resolve_token evals it — which is what lets it reference $QUARTERBACK_AGENT, a
  # variable qb_load_config sets only AFTER sourcing this file. That is also why a single
  # quote inside the value is an assertion below and not a comment: it would terminate the
  # quoting and turn the rest of the command into config-file syntax.
  configText = ''
    # Generated by programs.quarterback-harness (quarterback's hm-module.nix).
    # Do not edit — change the nix and rebuild.
    QUARTERBACK_BASE_URL=${toString board.url}
  '' + lib.optionalString (board.tokenCommand != null) ''
    QUARTERBACK_TOKEN_CMD='${board.tokenCommand}'
  '' + lib.optionalString (board.tokenRefreshCommand != null) ''
    QUARTERBACK_TOKEN_REFRESH_CMD='${board.tokenRefreshCommand}'
  '' + lib.optionalString (board.agent != null) ''
    QUARTERBACK_AGENT=${board.agent}
  '' + lib.optionalString (board.repo != null) ''
    QUARTERBACK_REPO="${board.repo}"
  '';
in
{
  options.programs.quarterback-harness = {
    enable = lib.mkEnableOption "the quarterback agent harness (loops, worktree tooling, slash commands, board client)";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.callPackage ./package.nix { };
      defaultText = lib.literalExpression "pkgs.callPackage ./package.nix { }";
      description = "The harness package to install.";
    };

    commands = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "panel" "panel-review-pr" "review-pr"
        "epic" "lander" "loops" "fix-and-land" "fix-and-review"
        "fix-issue" "fix-issue-here"
        "wt" "drop-worktree" "tree-shake"
      ];
      description = ''
        Which slash commands to link into ~/.claude/commands. Defaults to all of
        them. Narrow it if the host already provides a command of the same name —
        home-manager will collide rather than silently pick a winner, which is
        the behaviour you want.
      '';
    };

    seats.enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Install the multiplexer `qb-seats` needs. The scripts themselves are in
        the package already — this only adds tmux, which is the one runtime
        dependency the harness cannot assume is present.

        Off by default, and that is deliberate rather than timid. A consumer
        typically enables this whole module once, for every host they own; a
        seat screen is something they want on ONE of them. Defaulting to on would
        push a package onto machines that will never run a seat — including work
        machines somebody else owns the disk of — as a side effect of enabling
        the loops and the worktree tooling, which is not a trade a default gets
        to make on their behalf.
      '';
    };

    installScripts = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Put create-worktree / remove-worktree / prune-worktrees / worktree-holder
        on PATH by adding the package to home.packages. Turn this off to take the
        loops and commands without the worktree tooling — the two halves are
        independent.

        The board wiring below does NOT depend on this: it invokes qb-claude-setup
        by store path and wires qb-hook by store path, so a host can have a working
        board client without the harness on PATH at all. What it loses is the part a
        human types — `qb sessions`, `qb-board`, `create-worktree`.
      '';
    };

    # ---- which board, and how this host proves who it is ---------------------
    board = {
      url = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "https://qb.example.org";
        description = ''
          The board this host talks to. Setting it makes this module render
          `~/.config/quarterback/config`, which is what qb-hook, qb, qb-mcp and the
          status line all read.

          Null means "I manage that file myself" — the module renders nothing and
          collides with nothing. It does NOT mean a default board: there is
          deliberately no fallback URL anywhere in the harness. A self-hosted board
          has no sensible default, and guessing one points an agent at somebody
          else's board — which is not hypothetical, since a personal board resolves
          on public DNS from an employer's machine.
        '';
      };

      tokenCommand = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "cat /run/secrets/quarterback-token";
        description = ''
          A command printing this machine's bearer token on stdout. A command rather
          than a path because the token source is the other thing that varies per
          site — a file rendered by a secrets agent, a read from a password manager,
          an ssh fetch into RAM on a host that keeps no durable credential.

          Kept cheap: it runs on every board call. It is evaluated by the shell after
          the config file is sourced, so it may reference $QUARTERBACK_AGENT.
        '';
      };

      tokenRefreshCommand = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = ''
          Used INSTEAD of `tokenCommand` after a confirmed 401. It exists because the
          two are not always the same command: where `tokenCommand` reads a cache,
          re-running it after a rotation returns the same stale bearer, so the refresh
          has to go past the cache to the source of truth. Defaults to `tokenCommand`,
          which is right wherever that already reads the authoritative copy.
        '';
      };

      agent = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        description = ''
          This machine's name on the board — the machine half of a `machine/name`
          identity, and the name the token is issued against. Defaults to the short
          hostname, resolved at runtime rather than baked in.
        '';
      };

      repo = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "$HOME/source/quarterback";
        description = ''
          A checkout of this repository, which `qb-mcp` needs for the MCP server's venv
          (`mcp/.venv`). Emitted double-quoted, so `$HOME` in the value is expanded when
          the config is sourced. Null leaves qb-mcp's own default ($HOME/source/quarterback).

          That the MCP shim needs a checkout at all is a packaging gap, not a design:
          the server has real dependencies and lives beside the HTTP client it shares,
          so the flake does not build it yet.
        '';
      };
    };

    # ---- the wiring that makes a board client out of an installed package ----
    claude = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Wire the board into Claude Code's loose user configs at activation:
          the lifecycle hooks in `~/.claude/settings.json`, the stdio MCP server in
          `~/.claude.json`, and the workflow doc's @import in `~/.claude/CLAUDE.md`.
          This is what turns an installed harness into a working board client —
          without it a host gets the slash commands and the loops and no board:
          no lease, no presence, no ask courier, no overlap detection, no sync advice.

          Turn it off to take the fragment and merge it yourself. `qb-claude-setup
          --print-fragment` prints exactly what this would have merged, with paths
          resolved, so the manual route cannot drift from the wired one.
        '';
      };

      activationAfter = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        example = [ "claudeBaseSettings" ];
        description = ''
          Extra home-manager activation entries this module's wiring must run AFTER.

          Name your own here if you also write `~/.claude/settings.json`. The merge
          this module performs is additive by identity — it replaces quarterback's own
          hook entries and keeps everybody else's — but a merge that replaces whole
          arrays (`jq -s '.[0] * .[1]'`, the usual spelling) will drop ours if it runs
          last, because `hooks.PostToolUse` is an array. That is order-dependence, and
          order-dependence between two repos' activation scripts is a live bug class
          here rather than a hypothetical.

          Being explicit is the fix. Relying on the DAG's tie-breaking between two
          entries that merely both come after `writeBoundary` is not a fix; it is the
          same bug with a coincidence holding it up. `qb-claude-setup --check` reports
          the state either way, and reports it per event, so a wiring that lost one
          array is nameable rather than mysterious.
        '';
      };

      workflowDoc = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Install `~/.claude/quarterback-workflow.md` — how to use the board, for the
          model rather than for the machine — and @import it from `~/.claude/CLAUDE.md`.

          The import is conditional on the file being installed, so turning this off
          leaves no dangling @import behind. The file is a store symlink and therefore
          read-only, which is correct for a doc nothing local should be editing.
        '';
      };

      registerMcp = lib.mkOption {
        type = lib.types.enum [ "auto" "always" "never" ];
        default = "auto";
        description = ''
          Register `qb-mcp` as a global stdio MCP server in `~/.claude.json`.

          `auto` registers it only when the shim could actually start — that is, when
          the interpreter it execs (`<board.repo>/mcp/.venv/bin/python`) exists. A
          registered server that cannot start means every session opens on a failed MCP
          connection, and `auto` self-heals on the next switch once the venv is built.
          `always` registers regardless, for a host that builds the venv after
          activation and would rather not switch twice.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    {
      assertions = [
        {
          # The value is emitted inside single quotes (see configText) and there is no
          # escaping that survives it: a `'` closes the quote and the remainder of the
          # command becomes config-file syntax, which fails as a *token lookup* at
          # runtime, on every board call, with no line pointing back at this option.
          assertion = board.tokenCommand == null || !(lib.hasInfix "'" board.tokenCommand);
          message = ''
            programs.quarterback-harness.board.tokenCommand must not contain a single
            quote — it is emitted single-quoted so it stays literal until the token is
            resolved. Use double quotes inside it, or wrap the command in a script and
            name that instead.
          '';
        }
        {
          assertion = board.tokenRefreshCommand == null || !(lib.hasInfix "'" board.tokenRefreshCommand);
          message = "programs.quarterback-harness.board.tokenRefreshCommand must not contain a single quote (see board.tokenCommand).";
        }
      ];

      # A board URL with no way to get a token is not an error — QUARTERBACK_TOKEN may
      # come from the environment on a host that keeps no credential of its own — but it
      # is almost always an oversight, and the failure is silent by design: qb-hook
      # no-ops when it cannot resolve a token, so the symptom is a host that simply
      # never appears on the board.
      warnings = lib.optional (wantConfig && board.tokenCommand == null) ''
        programs.quarterback-harness.board.url is set but board.tokenCommand is not.
        qb-hook resolves no token and will no-op silently, so this host will not appear
        on the board at all. Set board.tokenCommand, or export QUARTERBACK_TOKEN.
      '';

      home.packages =
        lib.optionals cfg.installScripts [ cfg.package ]
        # NOT wrapped into the package's PATH, unlike a build dependency would be.
        # The user attaches to tmux by hand, reattaches over ssh, and has their own
        # config for it — so it has to be the tmux they can see and configure, not
        # one hidden inside a wrapper where `tmux attach` from their own shell
        # would find a different binary.
        ++ lib.optionals cfg.seats.enable [ pkgs.tmux ];

      home.file = lib.mkMerge (
        # ~/.claude/loops is a store symlink, i.e. READ-ONLY. epic.py already
        # accounts for this by writing its run state to ~/.local/state/loops rather
        # than beside itself; anything added here must do the same.
        [{ ".claude/loops".source = "${share}/loops"; }]
        ++ map
          (name: { ".claude/commands/${name}.md".source = "${share}/commands/${name}.md"; })
          cfg.commands
        ++ lib.optional (cfg.claude.enable && cfg.claude.workflowDoc) {
          ".claude/quarterback-workflow.md".source = "${share}/claude/quarterback-workflow.md";
        }
      );
    }

    # The site config: only when this module has been told which board. See board.url.
    (lib.mkIf wantConfig {
      xdg.configFile."quarterback/config".text = configText;
    })

    # ---- the activation ------------------------------------------------------
    # An activation script and not `home.file`, because ~/.claude/settings.json has
    # several writers — the user edits it, Claude Code writes to it, and nix wants to
    # declare parts of it. A store symlink would make it read-only and break the app.
    # qb-claude-setup carries the merge (and the reasoning); this only decides when it
    # runs and what is on its PATH.
    #
    # Named quarterbackClaudeWiring rather than the obvious quarterbackClaude: an
    # activation attribute is a shared namespace, a consumer migrating off a hand-rolled
    # copy of this wiring very likely has one of those, and two definitions of one
    # attribute is not a merge — it is a build that fails for everyone who pins this.
    (lib.mkIf cfg.claude.enable {
      home.activation.quarterbackClaudeWiring =
        lib.hm.dag.entryAfter ([ "writeBoundary" ] ++ cfg.claude.activationAfter) ''
          export PATH="${lib.makeBinPath [ pkgs.jq pkgs.gnugrep pkgs.coreutils pkgs.diffutils ]}:$PATH"
          # `|| true`: a coordination board must never be the reason a switch fails. The
          # script is fail-soft internally too — this is the second belt, for the case
          # where it cannot even start.
          $DRY_RUN_CMD ${pkgs.bash}/bin/bash ${cfg.package}/bin/qb-claude-setup \
            --mcp ${cfg.claude.registerMcp} || true
        '';
    })
  ]);
}
